"""Mock tests for prusa/tools/printer.py.

All HTTP calls are intercepted with pytest-mock — no real printer required.
Run with:  python -m pytest prusa/tests/test_printer.py -v
"""

from __future__ import annotations

import pytest
import httpx
from unittest.mock import MagicMock, call

from prusa.tools.printer import (
    ConfigError,
    PrinterError,
    PrinterResult,
    push_to_printer,
)


# ─── mock helpers ─────────────────────────────────────────────────────────────

def _resp(status: int = 200, body: dict | None = None) -> MagicMock:
    """Build a fake httpx response."""
    m = MagicMock()
    m.status_code = status
    m.json.return_value = body or {}
    m.text = str(body or {})
    return m


# Canned API response fixtures
OCTO_VERSION  = {"server": "1.9.3", "api": "0.1"}
OCTO_UPLOAD   = {
    "done": True,
    "files": {
        "local": {
            "name": "test.gcode",
            "refs": {"resource": "http://octopi.local/api/files/local/test.gcode"},
        }
    },
}
OCTO_JOB_OK   = {"_": "204 No Content represented as 200 for simplicity"}

MOON_INFO     = {"result": {"klippy_connected": True, "klippy_state": "ready"}}
MOON_UPLOAD   = {"result": {"item": {"path": "test.gcode", "root": "gcodes"}}}
MOON_START_OK = {"result": "ok"}


# ─── missing config ───────────────────────────────────────────────────────────

class TestMissingConfig:
    def test_no_host_raises(self, monkeypatch):
        monkeypatch.delenv("PRINTER_HOST", raising=False)
        monkeypatch.delenv("PRINTER_API_KEY", raising=False)
        with pytest.raises(ConfigError, match="PRINTER_HOST"):
            push_to_printer("irrelevant.gcode")

    def test_no_api_key_raises(self, monkeypatch, tmp_path):
        monkeypatch.setenv("PRINTER_HOST", "http://printer.local")
        monkeypatch.delenv("PRINTER_API_KEY", raising=False)
        gcode = tmp_path / "test.gcode"
        gcode.write_text("; gcode\n")
        with pytest.raises(ConfigError, match="PRINTER_API_KEY"):
            push_to_printer(str(gcode))

    def test_missing_file_raises(self, monkeypatch, tmp_path):
        monkeypatch.setenv("PRINTER_HOST", "http://printer.local")
        monkeypatch.setenv("PRINTER_API_KEY", "key")
        with pytest.raises(FileNotFoundError):
            push_to_printer(str(tmp_path / "nonexistent.gcode"))

    def test_unreachable_host_raises_config_error(self, mocker, monkeypatch, tmp_path):
        monkeypatch.setenv("PRINTER_HOST", "http://nowhere.local")
        monkeypatch.setenv("PRINTER_API_KEY", "key")
        gcode = tmp_path / "test.gcode"
        gcode.write_text("; gcode\n")
        mocker.patch("httpx.get", side_effect=httpx.ConnectError("Connection refused"))
        with pytest.raises(ConfigError, match="unreachable"):
            push_to_printer(str(gcode))


# ─── OctoPrint ────────────────────────────────────────────────────────────────

class TestOctoPrint:
    HOST    = "http://octopi.local"
    API_KEY = "octo-test-key"

    @pytest.fixture(autouse=True)
    def _env(self, monkeypatch):
        monkeypatch.setenv("PRINTER_HOST", self.HOST)
        monkeypatch.setenv("PRINTER_API_KEY", self.API_KEY)

    @pytest.fixture
    def gcode(self, tmp_path) -> str:
        f = tmp_path / "test.gcode"
        f.write_text("; generated by PrusaSlicer\nG28\nG1 Z5\n")
        return str(f)

    # ── detection ──

    def test_detects_octoprint(self, mocker, gcode):
        mocker.patch("httpx.get", return_value=_resp(200, OCTO_VERSION))
        mocker.patch("httpx.post", return_value=_resp(200, OCTO_UPLOAD))
        result = push_to_printer(gcode)
        assert result.printer_type == "octoprint"

    # ── upload without start ──

    def test_upload_returns_result(self, mocker, gcode):
        mocker.patch("httpx.get", return_value=_resp(200, OCTO_VERSION))
        mocker.patch("httpx.post", return_value=_resp(200, OCTO_UPLOAD))

        result = push_to_printer(gcode, start_immediately=False)

        assert isinstance(result, PrinterResult)
        assert result.printer_type == "octoprint"
        assert result.filename == "test.gcode"
        assert "test.gcode" in result.upload_url
        assert result.job_id == "test.gcode"
        assert result.started is False

    def test_upload_only_one_post_call(self, mocker, gcode):
        mocker.patch("httpx.get", return_value=_resp(200, OCTO_VERSION))
        mock_post = mocker.patch("httpx.post", return_value=_resp(200, OCTO_UPLOAD))

        push_to_printer(gcode, start_immediately=False)

        assert mock_post.call_count == 1

    # ── upload with start ──

    def test_start_immediately_makes_two_post_calls(self, mocker, gcode):
        mocker.patch("httpx.get", return_value=_resp(200, OCTO_VERSION))
        mock_post = mocker.patch("httpx.post", return_value=_resp(200, OCTO_UPLOAD))

        result = push_to_printer(gcode, start_immediately=True)

        assert result.started is True
        assert mock_post.call_count == 2

    def test_start_immediately_posts_to_api_job(self, mocker, gcode):
        mocker.patch("httpx.get", return_value=_resp(200, OCTO_VERSION))
        mock_post = mocker.patch("httpx.post", return_value=_resp(200, OCTO_UPLOAD))

        push_to_printer(gcode, start_immediately=True)

        urls = [c.args[0] for c in mock_post.call_args_list]
        assert any("/api/job" in url for url in urls)

    # ── api key forwarded ──

    def test_api_key_in_upload_headers(self, mocker, gcode):
        mocker.patch("httpx.get", return_value=_resp(200, OCTO_VERSION))
        mock_post = mocker.patch("httpx.post", return_value=_resp(200, OCTO_UPLOAD))

        push_to_printer(gcode)

        upload_call = mock_post.call_args_list[0]
        headers = upload_call.kwargs.get("headers", {})
        assert headers.get("X-Api-Key") == self.API_KEY

    # ── error handling ──

    def test_upload_http_error_raises_printer_error(self, mocker, gcode):
        mocker.patch("httpx.get", return_value=_resp(200, OCTO_VERSION))
        mocker.patch("httpx.post", return_value=_resp(500, {"error": "disk full"}))

        with pytest.raises(PrinterError, match="500"):
            push_to_printer(gcode)

    def test_start_http_error_raises_printer_error(self, mocker, gcode):
        mocker.patch("httpx.get", return_value=_resp(200, OCTO_VERSION))
        # upload succeeds, start fails
        mocker.patch(
            "httpx.post",
            side_effect=[_resp(200, OCTO_UPLOAD), _resp(409, {"error": "already printing"})],
        )

        with pytest.raises(PrinterError, match="409"):
            push_to_printer(gcode, start_immediately=True)

    def test_upload_url_fallback_when_refs_missing(self, mocker, gcode):
        """If refs.resource is absent, fall back to constructed URL."""
        mocker.patch("httpx.get", return_value=_resp(200, OCTO_VERSION))
        mocker.patch(
            "httpx.post",
            return_value=_resp(200, {"done": True, "files": {"local": {"name": "test.gcode"}}}),
        )

        result = push_to_printer(gcode)
        assert result.upload_url == f"{self.HOST}/api/files/local/test.gcode"


# ─── Moonraker ────────────────────────────────────────────────────────────────

class TestMoonraker:
    HOST    = "http://moonraker.local:7125"
    API_KEY = "moonraker-test-key"

    @pytest.fixture(autouse=True)
    def _env(self, monkeypatch):
        monkeypatch.setenv("PRINTER_HOST", self.HOST)
        monkeypatch.setenv("PRINTER_API_KEY", self.API_KEY)

    @pytest.fixture
    def gcode(self, tmp_path) -> str:
        f = tmp_path / "test.gcode"
        f.write_text("; generated by PrusaSlicer\nG28\nG1 Z5\n")
        return str(f)

    @pytest.fixture
    def mock_get_moonraker(self, mocker):
        """Simulate OctoPrint detection miss + Moonraker detection hit."""
        return mocker.patch(
            "httpx.get",
            side_effect=[
                _resp(404, {}),            # OctoPrint /api/version → not found
                _resp(200, MOON_INFO),     # Moonraker /server/info → ok
            ],
        )

    # ── detection ──

    def test_detects_moonraker_when_octoprint_absent(self, mock_get_moonraker, mocker, gcode):
        mocker.patch("httpx.post", return_value=_resp(200, MOON_UPLOAD))
        result = push_to_printer(gcode)
        assert result.printer_type == "moonraker"

    def test_detection_falls_through_from_octoprint(self, mock_get_moonraker, mocker, gcode):
        mocker.patch("httpx.post", return_value=_resp(200, MOON_UPLOAD))
        push_to_printer(gcode)
        # both detection probes were made
        assert mock_get_moonraker.call_count == 2

    # ── upload without start ──

    def test_upload_returns_result(self, mock_get_moonraker, mocker, gcode):
        mocker.patch("httpx.post", return_value=_resp(200, MOON_UPLOAD))

        result = push_to_printer(gcode, start_immediately=False)

        assert isinstance(result, PrinterResult)
        assert result.printer_type == "moonraker"
        assert result.filename == "test.gcode"
        assert "test.gcode" in result.upload_url
        assert "gcodes" in result.upload_url
        assert result.started is False

    def test_upload_only_one_post_call(self, mock_get_moonraker, mocker, gcode):
        mock_post = mocker.patch("httpx.post", return_value=_resp(200, MOON_UPLOAD))

        push_to_printer(gcode, start_immediately=False)

        assert mock_post.call_count == 1

    # ── upload with start ──

    def test_start_immediately_makes_two_post_calls(self, mock_get_moonraker, mocker, gcode):
        mock_post = mocker.patch(
            "httpx.post",
            side_effect=[_resp(200, MOON_UPLOAD), _resp(200, MOON_START_OK)],
        )

        result = push_to_printer(gcode, start_immediately=True)

        assert result.started is True
        assert mock_post.call_count == 2

    def test_start_immediately_posts_to_print_start(self, mock_get_moonraker, mocker, gcode):
        mock_post = mocker.patch(
            "httpx.post",
            side_effect=[_resp(200, MOON_UPLOAD), _resp(200, MOON_START_OK)],
        )

        push_to_printer(gcode, start_immediately=True)

        urls = [c.args[0] for c in mock_post.call_args_list]
        assert any("/printer/print/start" in url for url in urls)

    def test_start_posts_filename_in_body(self, mock_get_moonraker, mocker, gcode):
        mock_post = mocker.patch(
            "httpx.post",
            side_effect=[_resp(200, MOON_UPLOAD), _resp(200, MOON_START_OK)],
        )

        push_to_printer(gcode, start_immediately=True)

        start_call = mock_post.call_args_list[1]
        assert start_call.kwargs.get("json", {}).get("filename") == "test.gcode"

    # ── api key forwarded ──

    def test_api_key_as_bearer_token(self, mock_get_moonraker, mocker, gcode):
        mock_post = mocker.patch("httpx.post", return_value=_resp(200, MOON_UPLOAD))

        push_to_printer(gcode)

        upload_call = mock_post.call_args_list[0]
        headers = upload_call.kwargs.get("headers", {})
        assert headers.get("Authorization") == f"Bearer {self.API_KEY}"

    # ── error handling ──

    def test_upload_http_error_raises_printer_error(self, mock_get_moonraker, mocker, gcode):
        mocker.patch("httpx.post", return_value=_resp(400, {"error": {"message": "bad path"}}))

        with pytest.raises(PrinterError, match="400"):
            push_to_printer(gcode)

    def test_no_matching_server_raises_config_error(self, mocker, monkeypatch, tmp_path):
        monkeypatch.setenv("PRINTER_HOST", "http://mystery.local")
        monkeypatch.setenv("PRINTER_API_KEY", "key")
        gcode = tmp_path / "x.gcode"
        gcode.write_text("; gcode\n")
        # Both endpoints return garbage — neither pattern matches
        mocker.patch("httpx.get", return_value=_resp(200, {"unknown": "format"}))

        with pytest.raises(ConfigError, match="No OctoPrint or Moonraker"):
            push_to_printer(str(gcode))
